// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL7VR6C9-3Lp19MxiydEWC6u7IC73W9JE',
    appId: '1:900234166367:web:58fa1a778022f2d27d1bea',
    messagingSenderId: '900234166367',
    projectId: 'dr-urticaria',
    authDomain: 'dr-urticaria.firebaseapp.com',
    storageBucket: 'dr-urticaria.firebasestorage.app',
    measurementId: 'G-PJKZEYYYH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUbTBc-8nFZwBOej5IfNvStVi_iREyM8Q',
    appId: '1:900234166367:android:2e8cf0361c90ebaa7d1bea',
    messagingSenderId: '900234166367',
    projectId: 'dr-urticaria',
    storageBucket: 'dr-urticaria.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCrm-fNZkSOe3nERCWDr9UtW29XNqM-Rk',
    appId: '1:900234166367:ios:e54554f80246518a7d1bea',
    messagingSenderId: '900234166367',
    projectId: 'dr-urticaria',
    storageBucket: 'dr-urticaria.firebasestorage.app',
    iosBundleId: 'com.example.drUrticaria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCrm-fNZkSOe3nERCWDr9UtW29XNqM-Rk',
    appId: '1:900234166367:ios:e54554f80246518a7d1bea',
    messagingSenderId: '900234166367',
    projectId: 'dr-urticaria',
    storageBucket: 'dr-urticaria.firebasestorage.app',
    iosBundleId: 'com.example.drUrticaria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL7VR6C9-3Lp19MxiydEWC6u7IC73W9JE',
    appId: '1:900234166367:web:0b741e7b67e4f1dc7d1bea',
    messagingSenderId: '900234166367',
    projectId: 'dr-urticaria',
    authDomain: 'dr-urticaria.firebaseapp.com',
    storageBucket: 'dr-urticaria.firebasestorage.app',
    measurementId: 'G-NVDJ5LGTJ7',
  );
}
